### ISSUE TITLE
Over-zealous crushing

### ISSUE THREAD

**Issue by griley** [tedconf/crushinator_helpers#1]
The helper isn't very specific about which hosts it will crush images for.  For example: 'my-branch.tedlive.ted.com' will be crushed.

Would recommend that we move to an explicit whitelist of hosts rather than trying to determine all the possible needs from a regex.  Is it possible to enumerate the hosts?

cc: @mtwentyman @redoPop

**Comment by ryanto** [comment]
This is updated in https://github.com/tedconf/crushinator_helpers/blob/master/app/helpers/crushinator_helpers/view_helpers.rb#L47-L57 - let me know if this whitelist is too wide and we can update it. 

I'm closing this ticket but feel free to reopen!
